const fullStackSkills = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring",
    "Hibernate",
    "C#",
    ".NET",
    "ASP.NET",
    "Ruby",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Firebase",
    "GraphQL",
    "RESTful API",
    "WebSocket",
    "Redux",
    "MobX",
    "Webpack",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "Heroku",
    "HTML5",
    "CSS3",
    "Sass",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "Ant Design",
    "jQuery",
    "TypeScript",
    "Next.js",
    "Gatsby",
    "Nuxt.js",
    "Electron",
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Objective-C",
    "C++",
    "Unity",
    "Blender",
    "Photoshop",
    "Illustrator",
    "Figma",
    "Sketch",
    "InVision",
    "Zeplin",
    "Adobe XD",
    "Visual Studio Code",
    "IntelliJ IDEA",
    "Eclipse",
    "PyCharm",
    "WebStorm",
    "Xcode",
    "Android Studio",
    "Postman",
    "Swagger",
    "Insomnia",
    "Wireshark",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitHub Actions",
    "Jira",
    "Confluence",
    "Slack",
    "Trello",
    "Asana",
    "Notion",
    "Basecamp",
    "Airtable",
    "Monday.com",
    "Google Workspace",
    "Microsoft Office",
    "Zoom",
    "Microsoft Teams",
    "Skype",
    "Discord",
    "WhatsApp",
    "Signal",
    "Telegram",
    "Outlook",
    "Gmail",
    "Yahoo Mail",
    "Thunderbird",
     // Soft Skills
     "Communication",
     "Teamwork",
     "Problem-solving",
     "Time Management",
     "Leadership",
     "Adaptability",
     "Creativity",
     "Critical Thinking",
     "Attention to Detail",
     "Interpersonal Skills",
     "Emotional Intelligence",
     "Decision Making",
     "Conflict Resolution",
     "Negotiation",
     "Stress Management",
     // Job Roles
     "Full Stack Developer",
     "Frontend Developer",
     "Backend Developer",
     "UI/UX Developer",
     "Mobile App Developer",
     "Web Developer",
     "Software Engineer",
     "DevOps Engineer",
     "Data Scientist",
     "Data Analyst",
     "Machine Learning Engineer",
     "Artificial Intelligence Specialist",
     "Cloud Engineer",
     "Cybersecurity Analyst",
     "Network Engineer",
     "System Administrator",
     "Database Administrator",
     "Product Manager",
     "Project Manager",
     "Business Analyst",
     "QA Engineer",
     "UX Designer",
     "UI Designer",
     "Graphic Designer",
     "Content Writer",
     "Technical Writer",
     "Marketing Specialist",
     "Sales Representative",
     "Customer Success Manager",
     "Human Resources Manager",
     "Financial Analyst",
     "Accountant",
    
  ];
  
  
  export default fullStackSkills